# Generated by Django 3.2.7 on 2024-03-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_auto_20240304_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='dob',
            field=models.CharField(max_length=200),
        ),
    ]
